'''
This code is used to find a list of real estate agencies that are
within "min" miles from 2 input addresses. The data was mined
from the website: "http://www.yellowpages.com/austin-tx/realtors".
The data was mined using a data mining extension called Data Miner
and the first 200 valid addresses were saved to a text file. Then,
the python package geopy was used to find the precise locations
of these addresses and find the distances between certain places.
Distance is calculated using Vincenty's formula. The list that is
returned gives the addresses of these real estate agencies based
on the yellow pages website.
'''

from geopy.geocoders import ArcGIS
from geopy.distance import vincenty
import numpy as np
import sys, operator

radius = 10 # Use this mile radius when searching for agencies

def closest(addr1, addr2):
	lst = []
	addr1 = geolocator.geocode(addr1, timeout=5)
	addr2 = geolocator.geocode(addr2, timeout=5)
	addr1 = (addr1.latitude, addr1.longitude)
	addr2 = (addr2.latitude, addr2.longitude)
	for i in range(len(data)):
		# Give at least 5 seconds to find the address
		# Here we use range [2:-1] to get rid of extraneous characters
		# generated by our numpy dtype=str
		target = geolocator.geocode(data[i][2:-1], timeout=5)
		target_coords = (target.latitude, target.longitude)
		distance1 = vincenty(addr1, target_coords).miles
		distance2 = vincenty(addr2, target_coords).miles
		if (distance1 <= radius) and (distance2 <= radius):
			lst.append((target, distance1 + distance2))
		# Now we sort based on total distance
		lst.sort(key=operator.itemgetter(1))
	return lst

# Load text file containing 200 total addresses of realtors
data = np.loadtxt('data.txt', delimiter='\n', dtype=str)
geolocator = ArcGIS() # Select the geolocator
addr1 = input("Please enter the first address: ")
addr2 = input("Please enter the second address: ")
print("Please wait while we find the nearest agencies... ")
lst = closest(addr1, addr2) # Call the function. This will take a moment
if (len(lst)) == 0:
	print("Could not find any agencies near these locations.")
else:
	print("Here is your list of agencies: ")
	for i in range(len(lst)):
		# Print all agencies within "radius"
		print("{}: {}".format(i + 1, lst[i][0]))